export default [
  { value: "+966", iso: "SA", label: "Saudi Arabia (+966)" },
  { value: "+20", iso: "EG", label: "Egypt (+20)" },
  { value: "+971", iso: "AE", label: "United Arab Emirates (+971)" },
  { value: "+965", iso: "KW", label: "Kuwait (+965)" },
  { value: "+973", iso: "BH", label: "Bahrain (+973)" },
  { value: "+974", iso: "QA", label: "Qatar (+974)" },
  { value: "+968", iso: "OM", label: "Oman (+968)" },
  { value: "+962", iso: "JO", label: "Jordan (+962)" },
  { value: "+961", iso: "LB", label: "Lebanon (+961)" },
  { value: "+1", iso: "US", label: "United States (+1)" },
  { value: "+44", iso: "GB", label: "United Kingdom (+44)" },
  { value: "+49", iso: "DE", label: "Germany (+49)" },
  { value: "+33", iso: "FR", label: "France (+33)" },
  { value: "+39", iso: "IT", label: "Italy (+39)" },
  { value: "+34", iso: "ES", label: "Spain (+34)" },
  { value: "+31", iso: "NL", label: "Netherlands (+31)" },
  { value: "+91", iso: "IN", label: "India (+91)" },
  { value: "+92", iso: "PK", label: "Pakistan (+92)" },
  { value: "+86", iso: "CN", label: "China (+86)" },
  { value: "+81", iso: "JP", label: "Japan (+81)" },
  { value: "+61", iso: "AU", label: "Australia (+61)" },
  { value: "+1", iso: "CA", label: "Canada (+1)" }
]
