// Navigation items — controlled purely by permissions (section-prefixed)
const navigationItems = [
  {
    header: 'menu.assistantMenu',
    i18n: true,
    permission: 'assistant.view-dashboard',
  },
  {
    title: 'menu.dashboard',
    i18n: true,
    route: 'assistant-dashboard',
    icon: 'HomeIcon',
    permission: 'assistant.view-dashboard',
  },
  {
    title: 'menu.clients',
    i18n: true,
    route: 'assistant-clients',
    icon: 'UsersIcon',
    permission: 'assistant.view-clients',
  },
  {
    title: 'menu.reservations',
    i18n: true,
    route: 'assistant-reservations',
    icon: 'CalendarIcon',
    permission: 'assistant.view-reservations',
  },
  {
    title: 'menu.waitingQueue',
    i18n: true,
    route: 'assistant-waiting-queue',
    icon: 'ListIcon',
    permission: 'assistant.view-waiting-queue',
  },
  {
    title: 'menu.financials',
    i18n: true,
    route: 'assistant-financials',
    icon: 'DollarSignIcon',
    permission: 'assistant.view-financials',
  },
  {
    title: 'transaction.transactions',
    i18n: true,
    route: 'assistant-transactions',
    icon: 'CreditCardIcon',
    permission: 'assistant.view-financials',
  },
  {
    title: 'services.myServices',
    i18n: true,
    route: 'assistant-services',
    icon: 'GridIcon',
    permission: 'assistant.view-dashboard',
    feature: 'services',
  },
  {
    title: 'purchases.purchases',
    i18n: true,
    route: 'assistant-purchases',
    icon: 'ShoppingCartIcon',
    permission: 'assistant.view-purchases',
  },
  {
    title: 'menu.help',
    i18n: true,
    route: 'assistant-help',
    icon: 'HelpCircleIcon',
    permission: 'assistant.view-dashboard',
  },
  {
    header: 'menu.doctorMenu',
    i18n: true,
    permission: 'doctor.view-dashboard',
  },
  {
    title: 'menu.dashboard',
    i18n: true,
    route: 'doctor-dashboard',
    icon: 'HomeIcon',
    permission: 'doctor.view-dashboard',
  },
  {
    title: 'menu.clients',
    i18n: true,
    route: 'doctor-clients',
    icon: 'UsersIcon',
    permission: 'doctor.view-clients',
  },
  {
    title: 'menu.myReservations',
    i18n: true,
    route: 'doctor-reservations',
    icon: 'ClipboardIcon',
    permission: 'doctor.view-reservations',
  },
  {
    title: 'menu.schedule',
    i18n: true,
    route: 'doctor-schedule',
    icon: 'ClockIcon',
    permission: 'doctor.view-schedule',
  },
  {
    title: 'menu.waitingQueue',
    i18n: true,
    route: 'doctor-waiting-queue',
    icon: 'ListIcon',
    permission: 'doctor.view-waiting-queue',
  },
  {
    title: 'menu.financials',
    i18n: true,
    route: 'doctor-financials',
    icon: 'DollarSignIcon',
    permission: 'doctor.view-financials',
  },
  {
    title: 'transaction.transactions',
    i18n: true,
    route: 'doctor-transactions',
    icon: 'CreditCardIcon',
    permission: 'doctor.view-financials',
  },
  {
    title: 'purchases.purchases',
    i18n: true,
    route: 'doctor-purchases',
    icon: 'ShoppingCartIcon',
    permission: 'doctor.view-purchases',
  },
  {
    title: 'menu.assistants',
    i18n: true,
    route: 'doctor-assistants',
    icon: 'UserPlusIcon',
    permission: 'doctor.view-assistants',
  },
  {
    title: 'subDoctors.title',
    i18n: true,
    route: 'doctor-sub-doctors',
    icon: 'UsersIcon',
    permission: 'doctor.view-assistants',
  },
  {
    title: 'services.myServices',
    i18n: true,
    route: 'doctor-services',
    icon: 'GridIcon',
    permission: 'doctor.view-services',
    feature: 'services',
  },
  {
    title: 'menu.reports',
    i18n: true,
    route: 'doctor-reports',
    icon: 'BarChart2Icon',
    permission: 'doctor.view-reports',
    feature: 'reports',
  },
  {
    title: 'menu.help',
    i18n: true,
    route: 'doctor-help',
    icon: 'HelpCircleIcon',
    permission: 'doctor.view-reservations',
  },
  
  {
    header: 'menu.adminMenu',
    i18n: true,
    permission: 'admin.view-dashboard',
  },
  {
    title: 'menu.dashboard',
    i18n: true,
    route: 'admin-dashboard',
    icon: 'HomeIcon',
    permission: 'admin.view-dashboard',
  },
  {
    title: 'menu.rolesPermissions',
    i18n: true,
    route: 'admin-roles',
    icon: 'ShieldIcon',
    permission: 'admin.view-roles',
  },
  {
    header: 'menu.clientMenu',
    i18n: true,
    permission: 'client.view-dashboard',
  },
  {
    title: 'menu.dashboard',
    i18n: true,
    route: 'dashboard',
    icon: 'HomeIcon',
    permission: 'client.view-dashboard',
  },
  {
    title: 'auth.changePassword',
    i18n: true,
    route: 'change-password',
    icon: 'LockIcon',
  },
]

export default navigationItems
