export default [
  {
    header: 'erp.navigation.platform',
    i18n: true,
    roles: ['super_admin'],
  },
  {
    title: 'erp.navigation.companies',
    i18n: true,
    route: 'super-admin-dashboard',
    icon: 'HomeIcon',
    roles: ['super_admin'],
  },
  {
    header: 'erp.navigation.system',
    i18n: true,
    permission: 'erp.reports.view',
  },
  {
    title: 'erp.navigation.dashboard',
    i18n: true,
    route: 'erp-dashboard',
    icon: 'GridIcon',
    permission: 'erp.reports.view',
  },
  {
    title: 'erp.navigation.products',
    i18n: true,
    route: 'erp-products',
    icon: 'PackageIcon',
    permission: 'erp.products.view',
  },
  {
    title: 'erp.navigation.customers',
    i18n: true,
    route: 'erp-customers',
    icon: 'UsersIcon',
    permission: 'erp.customers.view',
  },
  {
    title: 'erp.navigation.suppliers',
    i18n: true,
    route: 'erp-suppliers',
    icon: 'TruckIcon',
    permission: 'erp.suppliers.view',
  },
  {
    title: 'erp.navigation.rawMaterials',
    i18n: true,
    route: 'erp-raw-materials',
    icon: 'BoxIcon',
    permission: 'erp.raw-materials.view',
  },
  {
    title: 'erp.navigation.rawMaterialPurchases',
    i18n: true,
    route: 'erp-raw-material-purchases',
    icon: 'ShoppingCartIcon',
    permission: 'erp.raw-material-purchases.view',
  },
  {
    title: 'erp.navigation.rawMaterialPayments',
    i18n: true,
    route: 'erp-raw-material-payments',
    icon: 'DollarSignIcon',
    permission: 'erp.raw-material-payments.view',
  },
  {
    title: 'erp.navigation.rawMaterialOperations',
    i18n: true,
    route: 'erp-raw-material-operations',
    icon: 'RepeatIcon',
    permission: 'erp.raw-material-operations.view',
  },
  {
    title: 'erp.navigation.invoices',
    i18n: true,
    route: 'erp-invoices',
    icon: 'FileTextIcon',
    permission: 'erp.invoices.view',
  },
  {
    title: 'erp.navigation.operations',
    i18n: true,
    route: 'erp-operations',
    icon: 'ActivityIcon',
    permission: 'erp.inventory.view',
  },
  {
    title: 'erp.navigation.payments',
    i18n: true,
    route: 'erp-payments',
    icon: 'CreditCardIcon',
    permission: 'erp.invoice-payments.view',
  },
  {
    title: 'erp.navigation.expenses',
    i18n: true,
    route: 'erp-expenses',
    icon: 'TrendingDownIcon',
    permission: 'erp.expenses.view',
  },
  {
    title: 'erp.navigation.inventory',
    i18n: true,
    route: 'erp-inventory',
    icon: 'LayersIcon',
    permission: 'erp.inventory.view',
  },
  {
    title: 'erp.navigation.employees',
    i18n: true,
    route: 'erp-employees',
    icon: 'BriefcaseIcon',
    permission: 'erp.employees.view',
  },
  {
    title: 'erp.navigation.salaries',
    i18n: true,
    route: 'erp-salaries',
    icon: 'DollarSignIcon',
    permission: 'erp.salaries.view',
  },
  {
    title: 'erp.navigation.reports',
    i18n: true,
    route: 'erp-reports',
    icon: 'BarChart2Icon',
    permission: 'erp.reports.view',
  },
  {
    title: 'erp.navigation.accessControl',
    i18n: true,
    route: 'erp-access-control',
    icon: 'UserPlusIcon',
    permission: 'erp.access.view',
  },
]
